// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://dglzjacbibsuaulptpwo.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnbHpqYWNiaWJzdWF1bHB0cHdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMyNDA5MTYsImV4cCI6MjA0ODgxNjkxNn0.F4X94W5HEF2MjOJ4bqYk7zrYVNJP15iFjAXy-t5M1CY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);